/**登录状态 */
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
    /** 退出 */
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

/**查询客户状态 */
export const GET_LN_CUSTS_SUCCESS = 'GET_LN_CUSTS_SUCCESS'
export const GET_LN_CUSTS_FAILED = 'GET_LN_CUSTS_FAILED'
    /**搜索客户列表状态 */
export const SEARCH_LN_CUSTS_SUCCESS = 'SEARCH_LN_CUSTS_SUCCESS'

/**查询客户列表状态 */
export const QUERY_BY_PAGE_LN_CUST_SUCCESS = 'QUERY_BY_PAGE_LN_CUST_SUCCESS'

export const GET_LN_CUST_SUCCESS = 'GET_LN_CUST_SUCCESS'
export const GET_LN_CUST_FAILED = 'GET_LN_CUST_FAILED'

/**查询定价单列表状态 */
export const GET_LN_PRICS_SUCCESS = 'GET_LN_PRICS_SUCCESS'
export const GET_LN_PRICS_FAILED = 'GET_LN_PRICS_FAILED'

export const GET_LN_BUSINESS_SUCCESS = 'GET_LN_BUSINESS_SUCCESS'
export const GET_LN_BUSINESS_FAILED = 'GET_LN_BUSINESS_FAILED'

/**查询定价单状态 */
export const GET_LN_PRIC_SUCCESS = 'GET_LN_PRIC_SUCCESS'
export const GET_LN_PRIC_FAILED = 'GET_LN_PRIC_FAILED'

/**删除定价单状态 */
export const DELETE_LN_PRIC_SUCCESS = 'DELETE_LN_PRIC_SUCCESS'
export const DELETE_LN_PRIC_FAILED = 'DELETE_LN_PRIC_FAILED'
    /**查询贷款抵押品状态 */
export const SAVE_LN_PRIC_MORTS_SUCCESS = 'SAVE_LN_PRIC_MORTS_SUCCESS'
export const SAVE_LN_PRIC_MORTS_FAILED = 'SAVE_LN_PRIC_MORTS_FAILED'

/**保存抵押品 */
export const GET_LN_PRIC_MORTS_SUCCESS = 'GET_LN_PRIC_MORTS_SUCCESS'
export const GET_LN_PRIC_MORTS_FAILED = 'GET_LN_PRIC_MORTS_FAILED'

/**查询贷款担保人状态 */
export const GET_LN_PRIC_GUARANTE_SUCCESS = 'GET_LN_PRIC_GUARANTE_SUCCESS'
export const GET_LN_PRIC_GUARANTE_FAILED = 'GET_LN_PRIC_GUARANTE_FAILED'

/**查询贷款派生存款状态 */
export const GET_LN_PRIC_SCENE_DP_SUCCESS = 'GET_LN_PRIC_SCENE_DP_SUCCESS'
export const GET_LN_PRIC_SCENE_DP_FAILED = 'GET_LN_PRIC_SCENE_DP_FAILED'

/**查询贷款派生中间状态 */
export const GET_LN_PRIC_SCENE_IB_SUCCESS = 'GET_LN_PRIC_SCENE_IB_SUCCESS'
export const GET_LN_PRIC_SCENE_IB_FAILED = 'GET_LN_PRIC_SCENE_IB_FAILED'


/**获取对公贷款定价单号 */
export const GET_LN_BUSINESS_CODE_SUCCESS = 'GET_LN_BUSINESS_CODE_SUCCESS'
export const GET_LN_BUSINESS_CODE_FAILED = 'GET_LN_BUSINESS_CODE_FAILED'


/**获取产品树 */
export const GET_TREE_SUCCESS = 'GET_TREE_SUCCESS'
export const GET_TREE_FAILED = 'GET_TREE_FAILED'


/**存入贷款基本信息 */
export const SET_LN_BASE_FORM_SUCCESS = 'SET_LN_BASE_FORM_SUCCESS'
    /**存入抵押品信息 */
export const SET_LN_BASE_MORTS_SUCCESS = 'SET_LN_BASE_MORTS_SUCCESS'
    /**存入担保人信息 */
export const SET_LN_BASE_GUARANTES_SUCCESS = 'SET_LN_BASE_GUARANTES_SUCCESS'
    /**更新Message */
export const SET_MESSAGE_SUCCESS = 'SET_MESSAGE_SUCCESS'

/**保存贷款几本信息*/
export const SAVE_LN_PRICING_INFO_SUCCESS = 'SAVE_LN_PRICING_INFO_SUCCESS'
export const SAVE_LN_PRICING_INFO_FAILED = 'SAVE_LN_PRICING_INFO_FAILED'

/**获取担保人信息*/
export const GET_LN_GUARANTES_SUCCESS = 'GET_LN_GUARANTES_SUCCESS'
export const GET_LN_GUARANTES_FAILED = 'GET_LN_GUARANTES_FAILED'

/**保存担保人 */
export const SAVE_LN_GUARANTE_SUCCESS = 'SAVE_LN_GUARANTE_SUCCESS'
export const SAVE_LN_GUARANTE_FAILED = 'SAVE_LN_GUARANTE_FAILED'

/**删除担保人 */
export const DELETE_LN_GUARANTE_SUCCESS = 'DELETE_LN_GUARANTE_SUCCESS'
export const DELETE_LN_GUARANTE_FAILED = 'DELETE_LN_GUARANTE_FAILED'
export const DELETE_LN_GUARANTE_STATE = 'DELETE_LN_GUARANTE_STATE'

/**贷款基准定价**/
export const LN_BASE_PRICING_SUCCESS = 'LN_BASE_PRICING_SUCCESS'
export const LN_BASE_PRICING_FAILED = 'LN_BASE_PRICING_FAILED'

/**贷款反算**/
export const LN_INVERSE_PRICING_SUCCESS = 'LN_INVERSE_PRICING_SUCCESS'
export const LN_INVERSE_PRICING_FAILED = 'LN_INVERSE_PRICING_FAILED'

/**保存贷款定价单**/
export const SAVE_LN_PRICING_SUCCESS = 'SAVE_LN_PRICING_SUCCESS'
export const SAVE_LN_PRICING_FAILED = 'SAVE_LN_PRICING_FAILED'

/**派生存款优惠 */
export const ADD_LN_PRIC_SCENE_DP_SUCCESS = "ADD_LN_PRIC_SCENE_DP_SUCCESS"
export const ADD_LN_PRIC_SCENE_DP_FAILED = "ADD_LN_PRIC_SCENE_DP_FAILED"

export const DEL_LN_PRIC_SCENE_DP_SUCCESS = "DEL_LN_PRIC_SCENE_DP_SUCCESS"
export const DEL_LN_PRIC_SCENE_DP_FAILED = "DEL_LN_PRIC_SCENE_DP_FAILED"

/**派生中间优惠 */
export const ADD_LN_PRIC_SCENE_IB_SUCCESS = "ADD_LN_PRIC_SCENE_IB_SUCCESS"
export const ADD_LN_PRIC_SCENE_IB_FAILED = "ADD_LN_PRIC_SCENE_IB_FAILED"

export const DEL_LN_PRIC_SCENE_IB_SUCCESS = "DEL_LN_PRIC_SCENE_IB_SUCCESS"
export const DEL_LN_PRIC_SCENE_IB_FAILED = "DEL_LN_PRIC_SCENE_IB_FAILED"

// 工作流
export const GET_APPROVE_LIST_SUCCESS = "GET_APPROVE_LIST_SUCCESS"
export const GET_APPROVE_LIST_FAILED = "GET_APPROVE_LIST_FAILED"

export const GET_APPROVE_SNAPSHOT_SUCCESS = "GET_APPROVE_SNAPSHOT_SUCCESS"
export const GET_APPROVE_SNAPSHOT_FAILED = "GET_APPROVE_SNAPSHOT_FAILED"

export const SUBMIT_APPROVE_SUCCESS = "SUBMIT_APPROVE_SUCCESS"
export const SUBMIT_APPROVE_FAILED = "SUBMIT_APPROVE_FAILED"

export const ALLOW_APPROVE_SUCCESS = "ALLOW_APPROVE_SUCCESS"
export const ALLOW_APPROVE_FAILED = "ALLOW_APPROVE_FAILED"

export const REJECT_APPROVE_SUCCESS = "REJECT_APPROVE_SUCCESS"
export const REJECT_APPROVE_FAILED = "REJECT_APPROVE_FAILED"